// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpk0JyXEBwTW3i7mvhQOxXMYmS918tUxg',
    appId: '1:47634091163:android:59088646a7bd8fe3d14a3e',
    messagingSenderId: '47634091163',
    projectId: 'pingwave-ca4da',
    storageBucket: 'pingwave-ca4da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8m_IUzNny9Oa-i29SA754H5KPJWh4Mg',
    appId: '1:47634091163:ios:6a4138746219a1d5d14a3e',
    messagingSenderId: '47634091163',
    projectId: 'pingwave-ca4da',
    storageBucket: 'pingwave-ca4da.appspot.com',
    iosBundleId: 'com.example.pingWave',
  );
}
